services:
  - type: web
    name: migu-live-source
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MIGU_RATE_TYPE
        value: "3"
      - key: MIGU_IGNORE_CATEGORY
        value: "TV"
      - key: MIGU_ENABLE_H265
        value: "true"
    healthCheckPath: /health
    autoDeploy: true
